PROMPTS = [
    {
        "id": "apple",
        "target_word": "apple",
        "acceptable_answers": ["apple", "red apple", "green apple"],
        "concept_description": "A common fruit that grows on trees and is often red, green, or yellow.",
        "difficulty": "Easy",
        "search_query": "red apple fruit",
        "fallback_image": "\U0001F34E",
        "credit_name": "Unsplash",
        "credit_url": "https://unsplash.com",
        "hint": "It is a fruit you can hold in one hand.",
    },
    {
        "id": "ball",
        "target_word": "ball",
        "acceptable_answers": ["ball", "soccer ball", "sports ball"],
        "concept_description": "A round object used in many games and sports.",
        "difficulty": "Easy",
        "search_query": "ball sports toy",
        "fallback_image": "\u26bd",
        "credit_name": "Unsplash",
        "credit_url": "https://unsplash.com",
        "hint": "It is round and you can throw, kick, or catch it.",
    },
    {
        "id": "chair",
        "target_word": "chair",
        "acceptable_answers": ["chair", "seat"],
        "concept_description": "A piece of furniture that people sit on.",
        "difficulty": "Easy",
        "search_query": "wooden chair furniture",
        "fallback_image": "\U0001FA91",
        "credit_name": "Unsplash",
        "credit_url": "https://unsplash.com",
        "hint": "People use it when they want to sit down.",
    },
    {
        "id": "umbrella",
        "target_word": "umbrella",
        "acceptable_answers": ["umbrella", "rain umbrella"],
        "concept_description": "A tool people hold above themselves to stay dry from rain.",
        "difficulty": "Normal",
        "search_query": "umbrella rain weather",
        "fallback_image": "\u2602\ufe0f",
        "credit_name": "Unsplash",
        "credit_url": "https://unsplash.com",
        "hint": "People use it outside when the weather is wet.",
    },
    {
        "id": "bicycle",
        "target_word": "bicycle",
        "acceptable_answers": ["bicycle", "bike"],
        "concept_description": "A two-wheeled vehicle powered by pedaling.",
        "difficulty": "Normal",
        "search_query": "bicycle city street",
        "fallback_image": "\U0001F6B2",
        "credit_name": "Unsplash",
        "credit_url": "https://unsplash.com",
        "hint": "It has two wheels and pedals.",
    },
    {
        "id": "stethoscope",
        "target_word": "stethoscope",
        "acceptable_answers": ["stethoscope"],
        "concept_description": "A medical tool used for listening to sounds inside the body.",
        "difficulty": "Hard",
        "search_query": "stethoscope doctor medical",
        "fallback_image": "\U0001FA7A",
        "credit_name": "Unsplash",
        "credit_url": "https://unsplash.com",
        "hint": "Doctors use it to listen to your heartbeat.",
    },
]
